# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e518677bde19f61037580a6cb7f5c4cc06386351a40341fb10f0fee6fc61e631d60ce502af35057b42b6236067516f713fc9f72124e20525dbdbe0a769a2a90c

test:
  secret_key_base: da235185c1a14d952651cd7451677de7b69d30794d2c8718de8d439021043ae8c51e0479613ff11f222bc9192eb7878f2d6993581017e98fe9ac2bd80dd4dd45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
